apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: harbor.anaheim.cf-app.com/dev/projects-operator
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.IMAGE_TAG}}'
deploy:
  helm:
    releases:
    - name: projects-operator
      chartPath: helm/projects-operator/
      values:
        image: harbor.anaheim.cf-app.com/dev/projects-operator
      setValues:
        clusterRoleRef: acceptance-test-clusterrole
        imagePullPolicy: Always
      imageStrategy:
        fqn: {}
    flags:
      upgrade:
      - --install
      - --recreate-pods
