apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: projects-operator
build:
  artifacts:
  - image: projects-operator
  tagPolicy:
    envTemplate:
      template: '{{.REGISTRY_HOST}}/{{.REGISTRY_PROJECT}}/projects-operator:{{.DEV_IMAGE_TAG}}'
deploy:
  helm:
    flags:
      upgrade: [--install, --atomic]
    releases:
    - name: projects-operator
      namespace: projects-operator
      chartPath: helm/projects-operator
      valuesFiles:
      - helm/projects-operator/values.yaml
      recreatePods: true
      setValues:
        imagePullPolicy: "Always"
        clusterRoleRef: "acceptance-test-clusterrole"
        maxConcurrentReconciles: 4
      setValueTemplates:
        originalImageRegistry: '{{.REGISTRY_HOST}}'
        originalImageNamespace: '{{.REGISTRY_PROJECT}}'
        "images.kubeRbacProxy.originalNamespace": '{{.REGISTRY_PROJECT}}'
        "images.projectsOperator.tag": '{{.DEV_IMAGE_TAG}}'
