apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: projects-operator
build:
  artifacts:
  - image: harbor.anaheim.cf-app.com/dev/projects-operator
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_TAG}}'
deploy:
  helm:
    flags:
      upgrade: [--install]
    releases:
    - name: projects-operator
      namespace: projects-operator
      chartPath: helm/projects-operator
      valuesFiles:
      - helm/projects-operator/values.yaml
      recreatePods: true
      setValues:
        originalImageRegistry: harbor.anaheim.cf-app.com
        originalImageNamespace: dev
        imagePullPolicy: Always
        clusterRoleRef: acceptance-test-clusterrole
        maxConcurrentReconciles: 4
        "images.kubeRbacProxy.originalNamespace": dev
      setValueTemplates:
        "images.projectsOperator.tag": '{{.IMAGE_TAG}}'
