---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: projects-operator-listwebhook
      namespace: default
      path: /projects
  failurePolicy: Fail
  name: projectaccess
  rules:
  - apiGroups:
    - developerconsole.pivotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - patch
    resources:
    - projectaccesses
