replicaCount: 1

image: gcr.io/cf-ism-0/projects-operator:latest
imagePullPolicy: IfNotPresent
imagePullSecrets:
- name: registry-secret

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}

clusterRoleRef: "projects-operator-clusterrole-ref-rolebinding"

kubeRbacProxy:
  image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0

webhook:
  serviceAccount: default
  service:
    port: 443
