replicaCount: 1

image: gcr.io/cf-ism-0/projects-operator:latest
imagePullPolicy: IfNotPresent
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}

role:
  apiGroups: servicecatalog.k8s.io
  resources: servicebindings,serviceinstances,clusterservicebrokers,clusterserviceclasses,clusterserviceplans
  verbs: "*"

kubeRbacProxy:
  image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
