platform: linux

image_resource:
  type: registry-image
  source:
    repository: ismteam/ci
    tag: 0.0.5

inputs:
- name: marketplace-project

params:
- KUBECONFIG_FILE_CONTENTS:
- UAA_LOCATION:
- CLUSTER_LOCATION:
- CODY_PASSWORD:

run:
  path: marketplace-project/ci/shim
  args:
     - make
     - acceptance-tests
