platform: linux

image_resource:
  type: registry-image
  source:
    repository: ismteam/ci
    tag: 0.0.5

inputs:
- name: marketplace-project

params:
  CLUSTER_API_LOCATION:
  CLUSTER_NAME:
  CODY_PASSWORD:
  KUBECONFIG_FILE_CONTENTS:
  UAA_LOCATION:

run:
  path: marketplace-project/ci/shim
  args:
     - make
     - acceptance-tests
