platform: linux

image_resource:
  type: registry-image
  source:
    repository: ismteam/ci
    tag: latest

inputs:
- name: projects-operator

params:
  CLUSTER_API_LOCATION:
  CLUSTER_NAME:
  CODY_PASSWORD:
  KUBECONFIG_FILE_CONTENTS:
  UAA_LOCATION:

run:
  path: projects-operator/ci/shim
  args:
     - make
     - acceptance-tests
