platform: linux

image_resource:
  type: registry-image
  source:
    repository: ismteam/ci
    tag: latest

inputs:
- name: projects-operator
- name: version

outputs:
- name: archive

run:
  path: projects-operator/ci/scripts/assemble-build-artefact.sh
