platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

params:
  CONTEXT: projects-operator

inputs:
- name: projects-operator

outputs:
- name: image

run:
  path: build
