platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

params:
  CONTEXT: marketplace-project

inputs:
- name: marketplace-project

outputs:
- name: image

run:
  path: build
