platform: linux

image_resource:
  type: registry-image
  source:
    repository: ismteam/ci
    tag: 0.0.8

inputs:
- name: projects-operator

run:
  path: projects-operator/ci/shim
  args:
     - make
     - unit-tests
