#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: #@ data.values.instance + "-" + data.values.name + "-projectaccess-cluster-role"
rules:
- apiGroups:
  - projects.vmware.com
  resources:
  - projectaccesses
  verbs:
  - create
  - delete
  - get
