#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name:  #@ data.values.registry.secretName
type: kubernetes.io/dockerconfigjson
data:
  #@ registry_auth = base64.encode("{}:{}".format(data.values.registry.username, data.values.registry.password))
  #@ registry_creds = {"username": data.values.registry.username, "password": data.values.registry.password, "auth": registry_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.registry.hostname + '/' + data.values.registry.project: registry_creds}}))
