#!/usr/bin/env bash

: ${1?'missing name'}
: ${2?'missing instance'}
: ${3?'missing namespace'}

name="$1"
instance="$2"
namespace="$3"

if [[ ! -z ${CI} ]]; then
  dd if=/dev/urandom of=/root/.rnd bs=256 count=1
fi

set -euo pipefail

openssl req -nodes -new -x509 -days 365 -keyout /tmp/ca.key -out /tmp/ca.pem -subj "/CN=Admission Controller Webhook Project Operator CA"
openssl genrsa -out /tmp/webhook-server-tls.key 2048
openssl req -new -key /tmp/webhook-server-tls.key -subj "/CN=$instance-$name-webhook.$namespace.svc" \
    | openssl x509 -req -days 365 -CA /tmp/ca.pem -CAkey /tmp/ca.key -CAcreateserial -out /tmp/webhook-server-tls.crt