#!/bin/bash

set -euo pipefail

NAMESPACE=${NAMESPACE:-projects-operator}

main () {
  helm uninstall projects-operator --namespace "$NAMESPACE"
  kubectl get crds | awk '{print $1}' | grep projects.vmware.com | grep project | xargs kubectl delete crd
  kubectl delete namespace "$NAMESPACE"
}

main
