#!/usr/bin/env bash

set -euo pipefail

sed -i '.temp' \
    's/projects-manager-role/"{{ template "projects-operator.fullname" . }}-manager-role"/g' \
    helm/projects-operator/templates/manager-role.yaml

sed -i '.temp' \
    's/projectaccesses-manager-role/"{{ template "projects-operator.fullname" . }}-projectaccess-cluster-role"/g' \
    helm/projects-operator/templates/projectaccess-role.yaml

sed -i '.temp' \
    's/projects-leader-election-role/"{{ template "projects-operator.fullname" . }}-leader-election-role"/g' \
    helm/projects-operator/templates/leader-election-role.yaml

rm helm/projects-operator/templates/*.temp
