#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

set -euo pipefail

NAMESPACE="${NAMESPACE:-"projects-operator"}"

kapp delete -y -a projects-operator -n "$NAMESPACE"
