---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: marketplace-project-serviceaccount
  namespace: default


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ci-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-admin-serviceaccount
subjects:
- kind: ServiceAccount
  name: marketplace-project-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: ci-admin
  apiGroup: rbac.authorization.k8s.io
