jobs:
- name: absolute-unit
  plan:
  - get: marketplace-project
    trigger: true
  - task: unit
    file: marketplace-project/ci/tasks/unit.yml

- name: acceptance
  plan:
  - get: marketplace-project
    trigger: true
    passed: [absolute-unit]
  - task: acceptance
    file: marketplace-project/ci/tasks/acceptance.yml
    params:
      KUBECONFIG_FILE_CONTENTS: {{KUBECONFIG_FILE_CONTENTS}}
      UAA_LOCATION: {{UAA_LOCATION}}
      CLUSTER_API_LOCATION: {{CLUSTER_API_LOCATION}}
      CLUSTER_NAME: marketplace-project-ci
      CODY_PASSWORD: {{CODY_PASSWORD}}

- name: release
  plan:
  - get: version
    trigger: true
  - get: marketplace-project
    passed: [acceptance]
  - task: assemble-build-artefact
    file: marketplace-project/ci/tasks/assemble-build-artefact.yml
  - task: build-image
    privileged: true
    file: marketplace-project/ci/tasks/build-image.yml
  - task: deplab
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: pivotalnavcon/deplab-task}
      inputs:
      - name: marketplace-project
      - name: image
      - name: version
      outputs:
      - name: tagged-image
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          set -eu pipefail
          DPKG_FILENAME="tagged-image/projects-dpkg-$(cat version/version).txt"
          deplab --image-tar image/image.tar \
            --git marketplace-project \
            --output-tar tagged-image/image.tar \
            --dpkg-file ${DPKG_FILENAME}
  - put: build-artefacts
    params:
      file: archive/projects-operator-*.tgz
  - put: gcr-repository
    params:
      image: tagged-image/image.tar
      additional_tags: version/number
  - put: dpkg-list
    params:
      file: tagged-image/projects-dpkg-*.txt
  - put: marketplace-project
    params:
      repository: marketplace-project
      only_tag: true
      tag: version/number
      tag_prefix: v


- name: bump-major
  plan:
    - get: version
      params: {bump: major}
    - put: version
      params: {file: version/number}

- name: bump-minor
  plan:
    - get: version
      params: {bump: minor}
    - put: version
      params: {file: version/number}

- name: bump-patch
  plan:
    - get: version
      params: {bump: patch}
    - put: version
      params: {file: version/number}

resources:
- name: marketplace-project
  type: git
  icon: github-face
  source:
    private_key: {{MARKETPLACE_PROJECT_DEPLOY_KEY}}
    uri: git@github.com:pivotal/marketplace-project
    branch: master

- name: gcr-repository
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/cf-ism-0/marketplace-project
    username: _json_key
    password: {{GCR_SERVICE_ACCOUNT_KEY}}

- name: build-artefacts
  type: google-cloud-storage
  icon: harddisk
  source:
    bucket: marketplace-build-artefacts
    json_key: {{GCS_SERVICE_ACCOUNT_KEY}}
    regexp: project/projects-operator-(.*).tgz

- name: dpkg-list
  type: google-cloud-storage
  icon: format-list-bulleted
  source:
    bucket: marketplace-build-artefacts
    json_key: {{GCS_SERVICE_ACCOUNT_KEY}}
    regexp: project/projects-dpkg-(.*).txt

- name: version
  type: semver
  icon: one-up
  source:
    driver: gcs
    bucket: marketplace-build-artefacts
    json_key: {{GCS_SERVICE_ACCOUNT_KEY}}
    key: versions/project
    initial_version: 0.0.1

resource_types:
  - name: google-cloud-storage
    type: docker-image
    source:
      repository: frodenas/gcs-resource
