jobs:
- name: absolute-unit
  plan:
  - get: marketplace-project
    trigger: true
  - task: unit
    file: marketplace-project/ci/tasks/unit.yml

- name: acceptance
  plan:
  - get: marketplace-project
    trigger: true
    passed: [absolute-unit]
  - task: acceptance
    file: marketplace-project/ci/tasks/acceptance.yml
    params:
      KUBECONFIG_FILE_CONTENTS: {{KUBECONFIG_FILE_CONTENTS}}
      UAA_LOCATION: {{UAA_LOCATION}}
      CLUSTER_LOCATION: {{CLUSTER_LOCATION}}
      CODY_PASSWORD: {{CODY_PASSWORD}}

resources:
- name: marketplace-project
  type: git
  icon: github-face
  source:
    private_key: {{CONCOURSE_DEPLOY_KEY}}
    uri: git@github.com:pivotal-cf/marketplace-project
    branch: master

