jobs:
- name: absolute-unit
  plan:
  - get: marketplace-project
    trigger: true
  - task: unit
    file: marketplace-project/ci/tasks/unit.yml

- name: acceptance
  plan:
  - get: marketplace-project
    trigger: true
    passed: [absolute-unit]
  - task: acceptance
    file: marketplace-project/ci/tasks/acceptance.yml
    params:
      KUBECONFIG_FILE_CONTENTS: {{KUBECONFIG_FILE_CONTENTS}}
      UAA_LOCATION: {{UAA_LOCATION}}
      CLUSTER_API_LOCATION: {{CLUSTER_API_LOCATION}}
      CLUSTER_NAME: marketplace-project-ci
      CODY_PASSWORD: {{CODY_PASSWORD}}
- name: release
  plan:
  - get: version
    trigger: true
  - get: marketplace-project
    passed: [acceptance]
  - task: assemble-build-artefact
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ismteam/ci
          tag: 0.0.7
      inputs:
        - name: marketplace-project
        - name: version
      outputs:
        - name: archive
      run:
        path: marketplace-project/ci/scripts/assemble-build-artefact.sh
  - put: build-artefacts
    params:
      file: archive/projects-*.tgz
  - put: gcr-repository
    params:
      build: marketplace-project
      tag_file: version/number
  - put: marketplace-project
    params:
      repository: marketplace-project
      only_tag: true
      tag: version/number
      tag_prefix: v


- name: bump-major
  plan:
    - get: version
      params: {bump: major}
    - put: version
      params: {file: version/number}

- name: bump-minor
  plan:
    - get: version
      params: {bump: minor}
    - put: version
      params: {file: version/number}

- name: bump-patch
  plan:
    - get: version
      params: {bump: patch}
    - put: version
      params: {file: version/number}

resources:
- name: marketplace-project
  type: git
  icon: github-face
  source:
    private_key: {{CONCOURSE_DEPLOY_KEY}}
    uri: git@github.com:pivotal/marketplace-project
    branch: master

- name: gcr-repository
  type: docker-image
  icon: docker
  source:
    repository: gcr.io/cf-ism-0/marketplace-project
    username: _json_key
    password: {{GCR_SERVICE_ACCOUNT_KEY}}

- name: build-artefacts
  type: google-cloud-storage
  icon: harddisk
  source:
    bucket: marketplace-build-artefacts
    json_key: {{GCS_SERVICE_ACCOUNT_KEY}}
    regexp: project/projects-(.*).tgz

- name: version
  type: semver
  icon: one-up
  source:
    driver: gcs
    bucket: marketplace-build-artefacts
    json_key: {{GCS_SERVICE_ACCOUNT_KEY}}
    key: versions/project
    initial_version: 0.0.1

resource_types:
  - name: google-cloud-storage
    type: docker-image
    source:
      repository: frodenas/gcs-resource
