jobs:
- name: absolute-unit
  plan:
  - get: marketplace-project
    trigger: true
  - task: unit
    file: marketplace-project/ci/tasks/unit.yml

- name: acceptance
  plan:
  - get: marketplace-project
    trigger: true
    passed: [absolute-unit]
  - task: acceptance
    file: marketplace-project/ci/tasks/acceptance.yml
    params:
      KUBECONFIG_FILE_CONTENTS: {{KUBECONFIG_FILE_CONTENTS}}
      UAA_LOCATION: {{UAA_LOCATION}}
      CLUSTER_LOCATION: {{CLUSTER_LOCATION}}
      CODY_PASSWORD: {{CODY_PASSWORD}}
  - put: build-artefacts
    params:
      file: marketplace-project/config/crd/bases/marketplace.pivotal.io_projects.yaml
  - put: gcr-repository
    params:
      build: marketplace-project

resources:
- name: marketplace-project
  type: git
  icon: github-face
  source:
    private_key: {{CONCOURSE_DEPLOY_KEY}}
    uri: git@github.com:pivotal-cf/marketplace-project
    branch: master

- name: gcr-repository
  type: docker-image
  source:
    repository: gcr.io/cf-ism-0/marketplace-project
    username: _json_key
    password: {{GCR_SERVICE_ACCOUNT_KEY}}

- name: build-artefacts
  type: google-cloud-storage
  source:
    bucket: marketplace-build-artefacts
    json_key: {{GCS_SERVICE_ACCOUNT_KEY}}
    regexp: project/marketplace.pivotal.io_projects.yaml

resource_types:
  - name: google-cloud-storage
    type: docker-image
    source:
      repository: frodenas/gcs-resource
