# This file should be applied into the CI K8s Cluster.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-serviceaccount
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ci-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-admin-serviceaccount
subjects:
- kind: ServiceAccount
  name: ci-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: ci-admin
  apiGroup: rbac.authorization.k8s.io
