#!/usr/bin/env sh

export PATH="$PATH:/root/go/bin"
cd projects-operator

if [ -n "$KUBECONFIG_FILE_CONTENTS" ]; then
    mkdir -p "$HOME/.kube"
    echo "$KUBECONFIG_FILE_CONTENTS" > "$HOME/.kube/config"
fi

if [ -n "$GKE_SERVICE_ACCOUNT_KEY" ]; then
    echo "$GKE_SERVICE_ACCOUNT_KEY" > "$HOME/gke_service_account_key.json"
fi

"$@"
