apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "projects-operator.labels" . | indent 4 }}
  name: {{ template "projects-operator.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "projects-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "projects-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: "{{ .Values.kubeRbacProxy.image }}"
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
        - args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
          command:
            - /manager
          env:
            - name: CLUSTER_ROLE_REF
              value: {{ .Values.clusterRoleRef}}
            - name: MAX_CONCURRENT_RECONCILES
              value: "{{ .Values.maxConcurrentReconciles }}"
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: manager
          resources:
{{ toYaml .Values.resources | indent 12 }}
            {{- with .Values.nodeSelector }}
      nodeSelector:
            {{ toYaml . | indent 8 }}
            {{- end }}
            {{- with .Values.affinity }}
      affinity:
            {{ toYaml . | indent 8 }}
            {{- end }}
            {{- with .Values.tolerations }}
      tolerations:
            {{ toYaml . | indent 8 }}
            {{- end }}
      terminationGracePeriodSeconds: 10
