---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: "{{ template "projects-operator.fullname" . }}-leader-election-rolebinding"
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: "{{ template "projects-operator.fullname" . }}-leader-election-role"
subjects:
    - kind: ServiceAccount
      name: default
      namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: "{{ template "projects-operator.fullname" . }}-manager-rolebinding"
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: "{{ template "projects-operator.fullname" . }}-manager-role"
subjects:
    - kind: ServiceAccount
      name: default
      namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ template "projects-operator.fullname" . }}-clusterrole-ref-rolebinding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRoleRef }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: "{{ template "projects-operator.fullname" . }}-projectaccess-authenticated-cluster-rolebinding"
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: "{{  template "projects-operator.fullname" . }}-projectaccess-cluster-role"
  apiGroup: rbac.authorization.k8s.io
