{{ $tls := fromYaml ( include "projects-operator.gen-webhook-certs" . ) }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "projects-operator.fullname" . }}-webhook
  labels:
    app: {{ template "projects-operator.fullname" . }}-webhook
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    app: {{ template "projects-operator.fullname" . }}-webhook
  ports:
  - name: secure
    protocol: TCP
    port: {{ .Values.webhook.service.port }}
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "projects-operator.fullname" . }}-webhook
  labels:
    app: {{ template "projects-operator.fullname" . }}-webhook
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "projects-operator.fullname" . }}-webhook
  template:
    metadata:
      labels:
        app: {{ template "projects-operator.fullname" . }}-webhook
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        releaseRevision: "{{ .Release.Revision }}"
    spec:
      serviceAccountName: "{{ .Values.webhook.serviceAccount }}"
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - name: webhook
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          command:
            - /webhook
          env:
            - name: TLS_KEY_FILEPATH
              value: "/etc/certs/key.pem"
            - name: TLS_CERT_FILEPATH
              value: "/etc/certs/cert.pem"
          resources:
            limits:
              memory: 50Mi
              cpu: 300m
            requests:
              memory: 00Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-cert
              mountPath: /etc/certs
              readOnly: true
            - name: logs
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
      - name: webhook-cert
        secret:
          secretName: {{ template "projects-operator.fullname" . }}-webhook-cert
      - name: logs
        emptyDir: {}

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "projects-operator.fullname" . }}-webhook-configuration
webhooks:
- clientConfig:
    caBundle: "{{ $tls.caCert }}"
    service:
      name: {{ template "projects-operator.fullname" . }}-webhook
      path: /projectaccess
      namespace: "{{ .Release.Namespace }}"
  failurePolicy: Fail
  name: projectaccess.projects.pivotal.io
  rules:
  - apiGroups:
    - projects.pivotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - projectaccesses

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "projects-operator.fullname" . }}-creation-webhook-configuration
webhooks:
- clientConfig:
    caBundle: "{{ $tls.caCert }}"
    service:
      name: {{ template "projects-operator.fullname" . }}-webhook
      path: /project-create
      namespace: "{{ .Release.Namespace }}"
  failurePolicy: Fail
  name: project.projects.pivotal.io
  rules:
  - apiGroups:
    - projects.pivotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - projects

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "projects-operator.fullname" . }}-webhook-configuration
webhooks:
- clientConfig:
    caBundle: "{{ $tls.caCert }}"
    service:
      name: {{ template "projects-operator.fullname" . }}-webhook
      path: /project
      namespace: "{{ .Release.Namespace }}"
  failurePolicy: Fail
  name: project.projects.pivotal.io
  rules:
  - apiGroups:
    - projects.pivotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - projects

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "projects-operator.fullname" . }}-webhook-cert
data:
  cert.pem: "{{ $tls.clientCert }}"
  key.pem: "{{ $tls.clientKey }}"
